### ISSUE TITLE
Blank screen with usb/thunderbolt dock or usb-c -> hdmi or igpu

### ISSUE THREAD

**Issue by ikalco** [hyprwm/aquamarine#76]
basically AQ fails to modeset some limited hardware for reasons...
possibly related issues hyprwm/Hyprland#7321 #59 #40

### to test if you have this
get a [DRM log](https://wiki.hyprland.org/Crashes-and-Bugs/#debugging-drm-issues) and if it contains the below, then you have some hardware limitation
```
Requested display configuration exceeds system DDB limitations
```
btw @romanstingler made a script if you want to use it
https://github.com/romanstingler/scripts/blob/main/hyprland_drm_debug.sh

---

**known causes**
* limited graphics hardware, Ex. integrated graphics or old gpus trying to do 4k
* usb hub with limited bandwidth, Ex. it can't transmit 4k
* sometimes usb-c to hdmi cables. with limited bandwidth?
* thunderbolt dock with limited bandwidth

**it can show up in multiple ways**
* screen is on but not displaying anything
* in hyprland logs AQ spams `Invalid Argument` or `No format for output`
* in dmesg [DRM logs](https://wiki.hyprland.org/Crashes-and-Bugs/#debugging-drm-issues) repeating `Requested display configuration exceeds system DDB limitations`

**possible mitigations (untested)**
* lower resolution or refresh rate on monitors
* use a different hub or cable
* use a discrete gpu
* use less monitors
* play around with different monitor to plug configurations until it hopefully works

**Comment by stjernstrom** [comment]
@ikalco thanks for creating this issue! 

Just to get a better understanding of the problem, reading the description it seems like the evidence points to be hardware related.
In my case the exact same hardware works running 0.41 but if I exit and start 0.42 the external screen goes black

Anything that have changed in 0.42 that change the hardware requirements?

Happy to help doing more tests and debug if I can help, and until then I stay on 0.41 :)

**Comment by romanstingler** [comment]
@stjernstrom this is because hyprland <0.42 was based on wlroots and wlroots had this swapchain manager 
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4567/diffs

This code provides utilities for managing swapchains, which are sets of buffers used by the compositor for rendering frames.
Compositors first initialize the swapchain manager and prepare it with desired output states.
If a configuration works, the compositor can get the swapchains and render buffers before committing the configuration.
After a successful commit, the new swapchains are applied to the outputs.

**Comment by stjernstrom** [comment]
Thanks @romanstingler 

II can confirm that running lastest aq-git and hl-git (v0.42.0-122-gb0fca6ea) with env = AQ_NO_MODIFIERS,1 in the config fixes the problem I had and now my external screen works exactly like before!

Awesome work! I appreciates the effort and support!
