### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by Aissi17** [hyprwm/aquamarine#94]
I'm having an issue when trying to launch Hyprland. I get the following error message:
Hyprland: symbol lookup error: /usr/lib/libaquamarine.so.3: undefined symbol: _ZN9Hyprutils4Math6Mat3x3C1Ev

Has anyone encountered this issue before or know how to resolve it

**Comment by vaxerski** [comment]
recompile

**Comment by Aissi17** [comment]
> recompile

how can i do that ?

**Comment by vaxerski** [comment]
compile it again

**Comment by vaxerski** [comment]
if you are using a regular distro's packaging (arch, fedora), that's their fault and should not happen. If you compiled anything yourself, you should know how to do that.

Hyprland is not meant for beginners, and you should understand your system _yourself_.

I can't give you any commands because I do not live inside your pc.
